### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by bnvinay92** [aurae/android-junit5#1]
Android studio doesn't recognise the tests when I use this plugin.

**Comment by aurae** [comment]
Since Android Studio (more specifically, the Android Gradle Plugin) doesn't have native support for JUnit 5 tests yet, the `test` task doesn't recognize them as such right now. If you would like the JUnit 5 tests to be invoked alongside the other test cases, you could set up a task dependency on one of the `junitPlatform` tasks generated by this plugin - the output won't be as nicely formatted as expected from the `test` task though, until we gain the aforementioned native support.
